language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
jobs:
  include:
    - stage: "Coverage and Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
    - script:
        - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate()'
        - julia --project=coverage/ coverage/coverage.jl
